artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/talk2pankajx/datasets/raw/main/samsundata.zip
  local_data_file: artifacts/data_ingestion/samsundata.zip
  unzip_dir: arifacts/data_ingestion



